app = "tmkt-api"  # Your app name (change if needed)

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"  # Must match your FastAPI port

[http_service]
  internal_port = 8000  # Must match your FastAPI port
  force_https = true    # Auto-redirect HTTP → HTTPS
  auto_stop_machines = true
  auto_start_machines = true
  
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"  # Your health check endpoint
    protocol = "http"